// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWT1z0EFPPtC3I71lOnYnbkJAObhgYhOI',
    appId: '1:963449432492:web:8d809337412dd832c97209',
    messagingSenderId: '963449432492',
    projectId: 'icecreamapp-fb9eb',
    authDomain: 'icecreamapp-fb9eb.firebaseapp.com',
    storageBucket: 'icecreamapp-fb9eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0GmApmkiF103XAvd1ChPlgVVc2vbmHYE',
    appId: '1:963449432492:android:e5085cf42990adbec97209',
    messagingSenderId: '963449432492',
    projectId: 'icecreamapp-fb9eb',
    storageBucket: 'icecreamapp-fb9eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlUjTE0KXS7Xu2Ce2TBRHP5jUec4fnNZ8',
    appId: '1:963449432492:ios:8c9f8413e427dfe6c97209',
    messagingSenderId: '963449432492',
    projectId: 'icecreamapp-fb9eb',
    storageBucket: 'icecreamapp-fb9eb.firebasestorage.app',
    iosBundleId: 'com.hcr.icecreamapp.iceCreamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlUjTE0KXS7Xu2Ce2TBRHP5jUec4fnNZ8',
    appId: '1:963449432492:ios:8c9f8413e427dfe6c97209',
    messagingSenderId: '963449432492',
    projectId: 'icecreamapp-fb9eb',
    storageBucket: 'icecreamapp-fb9eb.firebasestorage.app',
    iosBundleId: 'com.hcr.icecreamapp.iceCreamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWT1z0EFPPtC3I71lOnYnbkJAObhgYhOI',
    appId: '1:963449432492:web:99fb4dc793516ea9c97209',
    messagingSenderId: '963449432492',
    projectId: 'icecreamapp-fb9eb',
    authDomain: 'icecreamapp-fb9eb.firebaseapp.com',
    storageBucket: 'icecreamapp-fb9eb.firebasestorage.app',
  );
}
